---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: istio-system
    istio-injection: disabled
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 12h
  url: https://istio-release.storage.googleapis.com/charts
---


apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: "1.25.*"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      version: "1.25.*"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    cni:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cni
      version: "1.25.*"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h