---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: kiali-operator
  name: kiali-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  interval: 12h
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: kiali-operator
      version: "2.8.*"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: kiali-operator
      interval: 12h
  values:
    cr.create: true
    cr.namespace: istio-system
    cr.spec.auth.strategy: "anonymous"