apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 1h
  targetNamespace: ghost
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: OCIRepository
        name: ghost-repo
        namespace: flux-system