apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ghost-repo
    namespace: flux-system