apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ghost-repo
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/ghost
  ref:
    tag: latest