apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.*"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        storageClass: gp2
        accessModes:
          - ReadWriteOnce
        size: 20Gi
    loki:
      auth_enabled: false
      storage:
        type: filesystem
        bucketNames:
          chunks: chunks
          ruler: ruler
          admin: admin
      schemaConfig:
        configs:
          - from: "2025-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage_config:
        filesystem:
          directory: /tmp/loki/chunks
      compactor:
        working_directory: /data/loki/compactor
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
      ruler:
        enable_api: true
      ingester:
        chunk_encoding: snappy
      
