apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: operator
      version: "7.0.*"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: minio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tenant
      version: "7.0.*"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: minio