apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.x"  # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    # Values are loaded from the values.yaml file
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      optional: true
